services:
  #  app:
  #    image: mcr.microsoft.com/devcontainers/base:ubuntu
  ##    volumes:
  ##      - /workspaces/PostgresqlDocker:/workspace:cached
  #    command: /bin/sh -c "while sleep 1000; do :; done" # Keep the container running
  #
  postgres:
#    在这里使用 postgres:13-alpine 镜像，这是一个轻量级的 PostgreSQL 容器镜像，否则codespace会报错，因为镜像太大
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sub
      POSTGRES_DB: mydatabase
      # 这两行是解决报错的关键
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
#      这里必须挂载数据卷，否则每次重启容器都会丢失数据
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      bash -c "
      echo 'host all all 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf &&
      docker-entrypoint.sh postgres
      "  
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1g

#  nacos:
#    image: nacos/nacos-server:latest
#    environment:
#      MODE: standalone
#      PREFER_HOST_MODE: hostname
#      SPRING_DATASOURCE_PLATFORM: postgresql
#    ports:
#      - "8848:8848"
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672" # AMQP protocol port
#      - "15672:15672" # HTTP management UI port


#
#volumes:
#  db-data:
#    driver: local # 使用本地卷
